### ISSUE TITLE
Patch the backstage project to support docker build using dind-rootless image

### ISSUE THREAD

**Issue by cmoulliard** [halkyonio/tap#21]
## To do

Refactor the bash install script to patch the backstage project in order to support to build the docs using the Mkdocs [python](https://www.mkdocs.org/) tool to:
- Have a new container running [dind-rootless](https://docs.docker.com/engine/security/rootless/)
- Configure the `techdocs.generator` and specifiy the image of mkdocs to be used

```
k patch pkgi tap -n tap-install -p '{"spec":{"paused":true}}' --type=merge
k patch pkgi tap-gui -n tap-install -p '{"spec":{"paused":true}}' --type=merge

cat <<EOF > tmp/tap-gui-dind-patch.yaml
spec:
  template:
    spec:
      containers:
      - command:
        - dockerd      
        - --host
        - tcp://127.0.0.1:2375
        image: docker:dind-rootless #registry.harbor.10.0.77.176.nip.io:32443/tap/dind-rootless
        imagePullPolicy: IfNotPresent
        name: dind-daemon
        resources: {}
        securityContext:
          privileged: true
          runAsUser: 0
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/certs
          name: ca-harbor
        - mountPath: /tmp
          name: tmp
        - mountPath: /output
          name: output
      - name: backstage
        env:
        - name: DOCKER_HOST
          value: tcp://localhost:2375
        volumeMounts:
        - mountPath: /tmp
          name: tmp
        - mountPath: /output
          name: output
      volumes:
      - name: ca-harbor
        secret:
          secretName: ca-harbor
      - emptyDir: {}
        name: tmp
      - emptyDir: {}
        name: output
EOF

k patch deploy server -n tap-gui --patch-file tmp/tap-gui-dind-patch.yaml

k get secret -n tap-gui app-config-ver-1 -o json | jq -r '.data."app-config.yaml"' | base64 -d > tap-gui-secret.yaml
cat <<EOF >> tap-gui-secret.yaml
techdocs:
  generator:
    dockerImage: ghcr.io/vrabbi/techdocs:v1.0.3
EOF

CM_CONTENT=`cat tap-gui-secret.yaml | base64 -w 0`
cat << EOF >> tap-gui-secret-patch.yaml
data:
  app-config.yaml: $CM_CONTENT
EOF

k patch secret -n tap-gui app-config-ver-1 --patch-file tap-gui-secret-patch.yaml
k patch deploy server -n tap-gui --patch-file tap-gui-dind-patch.yaml
k rollout status deployment server -n tap-gui
```

Thanks to vrabbi: https://github.com/vrabbi/local-tap-setup/blob/master/local-tap.sh#L685 :-)
